### ISSUE TITLE
Error erasing/making USB when upgrading to Big Sur 11.1

### ISSUE THREAD

**Issue by irpk91** [BenSova/Patched-Sur#154]
When you get to the stage of creating the install USB and it starts to erase it unmounts the icon and then after a brief moment it reappears and then starts creating the media.  After another brief moment I get this message.

Error 1x252
Password:Erasing disk: 0%... 10%...
Error erasing disk error number (-69888, 0)
An error occurred erasing the disk.

**Comment by nesha72** [comment]
I have the same problem , with update to Big Sur 11.1.  Also the same error I get from terminal , thus  is the probably bug from apple.

Last login: Sat Dec 19 08:32:28 on console

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
******-MacBook-Pro:~ ******$ sudo /Applications/Install\ macOS\ Big\ Sur.app/Contents/Resources/createinstallmedia --volume /Volumes/MyVolume
Password:
Ready to start.
To continue we need to erase the volume at /Volumes/MyVolume.
If you wish to continue type (Y) then press return: y
Erasing disk: 0%... 10%...
Error erasing disk error number (-69888, 0)
An error occurred erasing the disk.
******-MacBook-Pro:~ ******$

**Comment by BigMacOS** [comment]
Same issue, likely Apple. 
Waiting for 1.0 - will this be a Christmas gift before the end of the year? :)

**Comment by michaelyeg** [comment]
Same issue on Late 2013 27" iMac.

**Comment by irpk91** [comment]
I really hope next version solves the problem.    Hope Apple aren’t up to any nefarious tactics.    The laugh is Bug Sur actually runs better on my unsupported Mac than Catalina which it supported.    I had a lot of wake from sleep issues with it and it seemed to run very sluggish.    Mid/late 2012 machines are quite up to the job.
  
  
  
    
  

  
  
>

**Comment by fate8383** [comment]
I think this is a format issue of the usb disk. I had the same problem, so go to disk utility change format of the usb disk, fat32 or so and erase all from there. It will prompt use this for time machine, ignore that and then try patcher GUI from scratch. This should do it.

**Comment by BigMacOS** [comment]
Late 2013 27" iMac
Just tried FAT32 and the same error.

**Comment by PeterShaws** [comment]
Interestingly enough, I was just able to run `createinstallmedia` manually, then `micropatcher.sh`, and finally `install-setvars.sh`. Then I rebooted and everything went fine.

Running Big Sur 11.1 as of the time of this writing.

**Comment by BenSova** [comment]
Apparently Apple's services are out to get me again. Spotlight Indexing isn't helpful.

**Comment by BenSova** [comment]
> Same issue, likely Apple. 
> 
> Waiting for 1.0 - will this be a Christmas gift before the end of the year? :)

v0.1.0 or v1.0.0? v0.1.0 probably, I got a long way to go before v1.0.0

**Comment by t36campbell** [comment]
> Interestingly enough, I was just able to run `createinstallmedia` manually, then `micropatcher.sh`, and finally `install-setvars.sh`. Then I rebooted and everything went fine.
> 
> Running Big Sur 11.1 as of the time of this writing.

This process can be found @ [barrykn/big-sur-micropatcher](https://github.com/barrykn/big-sur-micropatcher#instructions-for-use)

**Comment by DougMiner** [comment]
Can someone plese post a step by step resolution to this? Ive tied the suggestions so far, but keep getting messages that it may lock me out if I continue. Thanks.

**Comment by asharpe245** [comment]
First of all, a big shout out to BenSova for investing the time to complete this.
I had this same problem with my flash drive but experimented to see why. I did much of the stuff here by others and found that I wasn't able to complete the flash drive install until I moved the install process to a Mac that was running Catalina. Generally, this is the requirement to make it work although I don't know why it wouldn't complete on a Mac with Big Sur.
I found that even though I had selected "Release" version, the flash drive was labeled "Install macOS Big Sur Beta" when formatted. This was not the case when I moved to the Catalina Mac. I hope that others find this helpful.

**Comment by BenSova** [comment]
That's just the name Patched Sur choose for your usb drive when it doesn't the initial erase (I never actually changed it when Big Sur was released). The other one got formatted by both Patched Sur and createinstallmedia (The thing that's bugging out) and for whatever reason I can't disable that.

**Comment by asharpe245** [comment]
What I noticed though (didn’t explain it properly) is that when I used the Catalina Mac, the flash drive label did not include the “Beta” portion. I know that it doesn’t make any sense but it may have been an issue when attempting to mount the drive with an unexpected name.

Just my experience…

Al

On Feb 2, 2021, at 2:08 PM, Ben Sova <notifications@github.com> wrote:


That's just the name Patched Sur choose for your usb drive when it doesn't the initial erase (I never actually changed it when Big Sur was released). The other one got formatted by both Patched Sur and createinstallmedia (The thing that's bugging out) and for whatever reason I can't disable that.

**Comment by DougMiner** [comment]
Thank you for this. I had thought of that, but did not have a Carolina Mac handy. Instead, I used big-sur-micropatcher/.0.5.1 and followed the instruction video by Mr. Macintosh. It worked. Kudos to the guys who figure this stuff out. 

“Imagination is more important than knowledge." Albert Einstein

**Comment by DougMiner** [comment]
I ended up using big-sur-micropatcher-0.5.1 and it worked / thanks for everything you do to help us luddites.

“Imagination is more important than knowledge." Albert Einstein

**Comment by BenSova** [comment]
> What I noticed though (didn’t explain it properly) is that when I used the Catalina Mac, the flash drive label did not include the “Beta” portion. I know that it doesn’t make any sense but it may have been an issue when attempting to mount the drive with an unexpected name.

It's Apple's services clashing with Apple's services. Your drive gets erased twice, once by Patched Sur and once my createinstallmedia. The first time, it get's named to Install macOS Big Sur Beta, because that's what Patched Sur was programed to do. It's completely expected and passed into createinstallmedia with that exact name. However, Spotlight prevents createinstallmedia for redundantly re-erasing you drive, which results in this error.

**Comment by DougMiner** [comment]
Given what you described, would simply manually re-naming the flash drive solve the issue?

“Imagination is more important than knowledge." Albert Einstein

**Comment by BenSova** [comment]
No. It's supposed to be what Patched Sur intentionally named it. This is a bug with spotlight not playing well with createinstallmedia.

**Comment by DaLuce2020** [comment]
Any update on this?

Error 1x252
Password:Erasing disk: 0%... 10%...
Error erasing disk error number (-69888, 0)
An error occurred erasing the disk.

**Comment by BenSova** [comment]
PLT: If there's an update, I will say it. This isn't my top priority right now, getting out v0.1.0 is.

**Comment by Alkdz** [comment]
I have the same Error what should I do with it ?

Error 1x252
Password:Erasing disk: 0%... 10%...
Error erasing disk error number (-69888, 0)
An error occurred erasing the disk

Another isuue is that :
also If I restart my Mac while holding alt option and choosing for example my USB my acount appears and it rejected my password even though its correct and I use it normally just fine.

thanks ben

**Comment by BigMacOS** [comment]
Credits to Bensova & a Reddit user with some minor adjustments:

When you get the error, load terminal and use

mdutil -i off "/Volumes/Install macOS Big Sur"

after waiting a few minutes run this


/Applications/Install\ macOS\ Big\ Sur.app/Contents/Resources/createinstallmedia --volume /Volumes/Install\ macOS\ Big\ Sur\ 

3. It was really slow, but after it succeeded, I ran

~/.patched-sur/big-sur-micropatcher/micropatcher.sh /Volumes/Install\ macOS\ Big\ Sur

4. Lastly, I ran

~/.patched-sur/big-sur-micropatcher/install-setvars.sh /Volumes/Install\ macOS\ Big\ Sur

5. Then I rebooted and the rest of the upgrade/installation went as expected.

**Comment by BenSova** [comment]
I made a commit (a321b3b), that should fix this. Anyone want to try out a build that shouldn't run into this error?

Of course you do! [Patched Sur.app.zip](https://github.com/BenSova/Patched-Sur/files/5969858/Patched.Sur.app.zip) **REMEMBER** This version will require you to right-click then press open since I did not sign it and it also still requires the Patched Sur dmg to be mounted since it has some required files.

**Comment by swissadolf** [comment]
https://youtu.be/Syc028EjFJQ
Here is the solution that worked for me

**Comment by BenSova** [comment]
I request that anyone, before using another solution, try what I need someone to test first because that helps me know whether or not it works and I can include that in my next release so that no one will have to run into this bug again.

> [Patched Sur.app.zip](https://github.com/BenSova/Patched-Sur/files/5969858/Patched.Sur.app.zip) **REMEMBER** This version will require you to right-click then press open since I did not sign it and it also still requires the Patched Sur dmg to be mounted since it has some required files on there.

**Comment by asharpe245** [comment]
I’m still not able to erase the flash drive without an error using a supported iMac with Big Sur. The drive is unmounted, renamed and mounted again, and then the same error pops up.

I’m going to try the update patch on my unsupported MacBook now.

Al

On Feb 12, 2021, at 9:32 AM, Ben Sova <notifications@github.com> wrote:


I request that anyone, before using another solution, try what I need someone to test first because that helps me know whether or not it works and I can include that in my next release so that no one will have to run into this bug again.

Patched Sur.app.zip <https://github.com/BenSova/Patched-Sur/files/5969858/Patched.Sur.app.zip> REMEMBER This version will require you to right-click then press open since I did not sign it and it also still requires the Patched Sur dmg to be mounted since it has some required files on there.

**Comment by BenSova** [comment]
I just updated the link. Someone else tested it and it didn't work, so I made a new one.

[Patched-Sur.app.zip](https://www.dropbox.com/s/33zgt7pylmzg7ig/Patched%20Sur%202.app.zip?dl=1)

**Comment by asharpe245** [comment]
Same error for me.

Error 1x252
Message: "Password:Erasing disk: 0%... 10%...
Error erasing disk error number (-69888, 0)
An error occurred erasing the disk."
Output: “"

Al

On Feb 12, 2021, at 10:42 AM, Ben Sova <notifications@github.com> wrote:


I just updated the link. Someone else tested it and it didn't work, so I made a new one.

Patched-Sur.app.zip <https://www.dropbox.com/s/33zgt7pylmzg7ig/Patched%20Sur%202.app.zip?dl=1>

**Comment by asharpe245** [comment]
No difference for me.

Error 1x252
Message: "Password:Erasing disk: 0%... 10%...
Error erasing disk error number (-69888, 0)
An error occurred erasing the disk."
Output: “"

I did run the Post Install App on an unsupported MacBook. I found that it worked, but it told me that there were no updates, when I know that 11.2.1 is now available.

Al

On Feb 12, 2021, at 10:42 AM, Ben Sova <notifications@github.com> wrote:


I just updated the link. Someone else tested it and it didn't work, so I made a new one.

Patched-Sur.app.zip <https://www.dropbox.com/s/33zgt7pylmzg7ig/Patched%20Sur%202.app.zip?dl=1>

**Comment by BenSova** [comment]
> I found that it worked, but it told me that there were no updates when I know that 11.2.1 is now available.
It's not available. There's no InstallAssistant.pkg. It's released for supported Macs, but there's no way we can put it on unsupported Macs.

**Comment by asharpe245** [comment]
It looks like it needs to be tricked into thinking it is supported so it will pull the update. I know that’s easier said then done.

Al

On Feb 12, 2021, at 11:02 AM, Ben Sova <notifications@github.com> wrote:


I found that it worked, but it told me that there were no updates when I know that 11.2.1 is now available.
It's not available. There's no InstallAssistant.pkg. It's released for supported Macs, but there's no way we can put it on unsupported Macs.

**Comment by BenSova** [comment]
[Patched Sur.app.zip](https://github.com/BenSova/Patched-Sur/files/5973038/Patched.Sur.-.For.Catalina.app.zip)

Now it kills `mds`, the leader of spotlight indexing (and the only thing that was using my BOOTCAMP partition).

**Comment by asharpe245** [comment]
Sometimes there is still a delay in trying to unmount the flash drive, and I get this:

Error 1x1
Message: "Error: -69888: Couldn't unmount disk"
Output: "Started erase on disk4
Unmounting disk
The volume on disk4 couldn't be unmounted because it is in use by process 3185 (mds_stores)”

If I load Patched Sur first, then mount my flash drive, I get this. Results may not be consistent.

Error 1x252
Message: "Password:Erasing disk: 0%... 10%...
Error erasing disk error number (-69888, 0)
An error occurred erasing the disk."
Output: “”

I don’t understand how the erase process can be at close to 20% and then it fails.

Just to be clear, I’ve been running the installer on a Big Sur supported Mac. When I run the installer on a Catalina Mac (dosdude1 patched), it runs as expected without errors. I know that’s the intent for the patcher, but those with only one Mac are going to have an issue with this once the complete the first upgrade from Catalina. If it were me, I would take what works and build a Catalina boot flash where I could run the Patched Sur installer.

I know you have put in significant time and effort into this and it is most appreciated by all that follow this.

Al


On Feb 12, 2021, at 11:21 AM, Ben Sova <notifications@github.com> wrote:


Patched Sur.app.zip <https://github.com/BenSova/Patched-Sur/files/5973038/Patched.Sur.-.For.Catalina.app.zip>
Now it kills mds, the leader of spotlight indexing (and the only thing that was using my BOOTCAMP partition).

**Comment by zurcatron** [comment]
Anybody know if there is a fix for Error 1x252 yet? Ive tried to update several times and still fails.

**Comment by DaLuce2020** [comment]
> Anybody know if there is a fix for Error 1x252 yet? Ive tried to update several times and still fails.

Disabling Spotlight worked for me.

**Comment by zurcatron** [comment]
> > Anybody know if there is a fix for Error 1x252 yet? Ive tried to update several times and still fails.
> 
> Disabling Spotlight worked for me.

I have Spotlight Disabled no luck with that -_-

**Comment by BenSova** [comment]
**Try this before any other solution:** [Patched Sur.zip](https://github.com/BenSova/Patched-Sur/files/5978478/Patched.Sur.zip)

I tried a different command inside Patched Sur this time.

**Comment by asharpe245** [comment]
This is looking very promising. It’s been running for over 10 minutes without showing an error. Nice work! 
I’ll update you when it finishes.

Al

On Feb 14, 2021, at 3:45 PM, Ben Sova <notifications@github.com> wrote:


Try this before any other solution: Patched Sur.zip <https://github.com/BenSova/Patched-Sur/files/5978478/Patched.Sur.zip>
I tried a different command inside Patched Sur this time.

**Comment by asharpe245** [comment]
I was installing without Patched-Sur.dmg not being launched. I did get an error about it but continued anyway. Then, I got this error after about 15 minutes of running:

Error 1x1
Message: "Password:sudo: /Volumes/Patched-Sur/.patch-usb.sh: command not found"
Output: “"

I closed everything and launched the .dmg, closed the patch app and opened the app you posted in the .zip file. Then my flash drive died so I got out another. This time it completed successfully after about 18 minutes.

Looks good!

Al


On Feb 14, 2021, at 4:06 PM, Al Sharpe <asharpe@rogers.com> wrote:

This is looking very promising. It’s been running for over 10 minutes without showing an error. Nice work! 
I’ll update you when it finishes.

Al

On Feb 14, 2021, at 3:45 PM, Ben Sova <notifications@github.com <mailto:notifications@github.com>> wrote:


Try this before any other solution: Patched Sur.zip <https://github.com/BenSova/Patched-Sur/files/5978478/Patched.Sur.zip>
I tried a different command inside Patched Sur this time.

**Comment by BenSova** [comment]
Nice! Yeah, I forgot to mention the Patched Sur DMG is still required (you should of gotten a popup saying that). Looks like I finally have a solution.

**Comment by BenSova** [comment]
Since this is finally fixed as of v0.0.7, this issue can be closed.

**Comment by pitoganzado** [comment]
hi to all.
I got "Error 1x1
Message: "Password:sudo: /Volumes/Patched-Sur/.patch-usb.sh: command not found"
Output: "" even with 0.0.7 version. Any help/workaround?

**Comment by swissadolf** [comment]
As there was a mistake, it is!
Don't be fooled.
thank

**Comment by jpasqua** [comment]
I am having this problem with a fresh download of v0.0.7 (49) when attempting to install 11.2.1. See screenshot.

I'm using the same external SSD that I did when I successfully installed 11.1.

Please let me know if I can provide any other information that might be helpful.

![Screen Shot 2021-02-21 at 5 04 37 PM](https://user-images.githubusercontent.com/3820906/108645263-19e7b080-7467-11eb-9e07-b895688ebd79.png)

**Comment by abdlmlaekluttei** [comment]
i faced the same error, i resolve the issue by formating the usb stick to FAT32 "MS_DOS FAT"

**Comment by jpasqua** [comment]
That worked! Thank you.

It got me one step closer but, sadly, I hit another issue. Even after the full process, the disk is not recognized as bootable. It is the same drive I used when I updated from Catalina using patched-sur. It is very likely to be an error on my part and I will continue to investigate.

**Comment by DougMiner** [comment]
I cannot get past the opening dialogue.It just refers me to the website and does not offer to download the OS. What am I doing wrong? I downloaded something called Install assistant at 12.2 Gb, but it wanted 34 to install and I only have 16 on my flash drive. Do I need a bigger drive?, Thanks.

**Comment by DougMiner** [comment]
I get error 1x252 no matter how the disk.

**Comment by kamilsj** [comment]
I am getting the same error. Is there any solution to this problem?

**Comment by ElBuru420** [comment]
I managed to pass through that error (so far im at 10% in the "copying to dick" process) by opening the activity monitor and keep force-quitting the "mds_stores" process. Just notice, if you wanna try this, to write "mds_stores" in the search bar (into the activity monitor) and make sure to keep force-quitting the process because it may keep reappearing.  

I will update if is works for me.

good luck fellas :D

**Comment by ElBuru420** [comment]
80% and so far so well

**Comment by ElBuru420** [comment]
90%....

**Comment by jpasqua** [comment]
I never managed to get this working, but I was able to upgrade seamlessly and easily using v0.1.1. Thanks @BenSova !

**Comment by garungwins** [comment]
Well for me its worked, i have format the usb on a windows pc, and used the comand in terminal with out to format first the usb on utility disk. and its work well

**Comment by ElBuru420** [comment]
> I never managed to get this working, but I was able to upgrade seamlessly and easily using v0.1.1. Thanks @BenSova !

I'm also using v0.1.1 but the error 1x252 is still there.

**Comment by DougMiner** [comment]
It took me several tries, but it eventually worked. It always failed at about 10% writing to disk. When it finally worked, it worked very well. It quit and re-booted into the new version of Big Sur. No need to boot off the flash drive at all.

**Comment by BenSova** [comment]
> I'm also using v0.1.1 but the error 1x252 is still there.

First of all, use v0.1.2. Second, he meant using the post-install updater.

> No need to boot off the flash drive at all.

That's with the post-install updater, not the pre-install app like this issue was talking about, so it's a different process that MDS doesn't mess with.

**Comment by DougMiner** [comment]
It might be helpful to name the post install app a bit differently. Maybe it’s just me, but I found it a bit confusing. I did eventually get it to work with v0.1.1 as it was the only one available at the time.

**Comment by ElBuru420** [comment]
Definitely'd be helpful. However, post-install app (v0.1.2) is working perfectly.

**Comment by Dotschko** [comment]
I had the same problem and this fixed it.

Annoyingly I turned off my antivirus but also changed USB stick from a 256gb Sandisk to a 64gb stick during the same installation. I am not sure which one fixed the issue but one did. I guess as Mac processes and spotlight have been an issue, it could be the antivirus.

**Comment by BenSova** [comment]
Anti-viruses are annoying to try to develop with. Sure, they're secure, but they're constantly messing with￼ everything. But yeah, if you're running Patched Sur, turn it off, they mess with the patcher a lot assuming it has to modify the system to work.
